# Generated by Django 3.2.12 on 2022-07-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logisticsapp', '0004_customuser_whatsup_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='emission_test_img',
            new_name='fitness_certificate_front_side_img',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='fitness_certificate_img',
            new_name='fitness_certificate_front_side_img_path',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='permit_img',
        ),
        migrations.AddField(
            model_name='customuser',
            name='adhar_card_back_side_img',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='adhar_card_back_side_img_path',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='adhar_card_front_side_img',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='adhar_card_front_side_img_path',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='permit_front_side_img',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='permit_front_side_img_path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='pollution_certificate_front_side_img',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='pollution_certificate_front_side_img_path',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='registration_certificate_back_side_img',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='registration_certificate_back_side_img_path',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='registration_certificate_front_side_img',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='registration_certificate_front_side_img_path',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
