# Generated by Django 3.2.12 on 2022-07-31 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logisticsapp', '0005_auto_20220729_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='create_timestamp',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='last_update_timestamp',
        ),
        migrations.AddField(
            model_name='customuser',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logisticsapp.driver'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logisticsapp.vehicle'),
        ),
    ]
