# Generated by Django 3.2.12 on 2022-07-31 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logisticsapp', '0008_auto_20220731_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='fitness_certificate_front_side_img',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='fitness_certificate_front_side_img_path',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
