# Generated by Django 3.2.12 on 2022-08-24 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logisticsapp', '0011_auto_20220812_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='live_lattitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='live_longitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
